[server]
headless = true
port = 8501

[theme]
primaryColor = "#d97706"
backgroundColor = "#080808"
secondaryBackgroundColor = "#111111"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false
